config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'config'), namespace='shop')),
    path('users/', include(('users.urls', 'config'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('products/', views.products_list, name='products'),
    path('cart/', views.cart, name='cart'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_item/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('orders/', views.orders, name='orders')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password')
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User

from shop.bulma_mixin import BulmaMixin


class SignUpForm(BulmaMixin, UserCreationForm):
    username = forms.CharField(label='Create username')
    email = forms.EmailField(label='Write email')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Create password')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Repeat password')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class SignInForm(BulmaMixin, AuthenticationForm):
    username = forms.CharField(label='Write username')
    password = forms.CharField(widget=forms.PasswordInput(), label='Write password')

    class Meta:
        model = User
        fields = ('username', 'password')


class EditProfileForm(BulmaMixin, forms.ModelForm):
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    username = forms.CharField(label='Username')
    email = forms.EmailField(label='Email address')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ResetPasswordForm(BulmaMixin, PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput, label='Old password')
    new_password1 = forms.CharField(widget=forms.PasswordInput, label='Create new password')
    new_password2 = forms.CharField(widget=forms.PasswordInput, label='Repeat new password')

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

users/views.py
from django.contrib.auth import login, logout, update_session_auth_hash
from django.shortcuts import render, redirect

from users.forms import SignUpForm, SignInForm, EditProfileForm, ResetPasswordForm


def sign_up(request):
    form = SignUpForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('users:sign_in')
    form = SignUpForm()
    return render(request, 'sign_up.html', {
        'form': form
    })


def sign_in(request):
    form = SignInForm(data=request.POST or None)
    if request.method == "POST" and form.is_valid():
        user = form.get_user()
        login(request, user)
        return redirect('shop:products')
    form = SignInForm()
    return render(request, 'sign_in.html', {
        'form': form
    })


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')


def edit_profile(request):
    form = EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        return redirect('shop:products')
    form = EditProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {
        'form': form
    })


def reset_password(request):
    form = ResetPasswordForm(request.user, request.POST)
    if form.is_valid() and request.method == 'POST':
        user = form.save()
        update_session_auth_hash(request, user)
        return redirect('users:sign_in')
    form = ResetPasswordForm(request.user)
    return render(request, 'reset_password.html', {'form': form})

users/templates/edit_profile.html
{% extends 'base.html' %}

{% block auth %}
    <div class="columns is-centered">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post" enctype="multipart/form-data">
                    <h1 class="title is-size-2 has-text-centered">Edit profile</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

users/templates/reset_password.html
{% extends 'base.html' %}

{% block auth %}
    <div class="columns is-centered">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Reset password</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

users/templates/sign_in.html
{% extends 'base.html' %}

{% block auth %}
    <div class="columns is-centered" style="margin-top: 6%">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Sign in</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                    <p class="content mt-3">
                        Already have an account?
                        <span>
                           <a href="{% url 'users:sign_up' %}">Sign in here</a>
                       </span>
                    </p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/sign_up.html
{% extends 'base.html' %}

{% block auth %}
    <div class="columns is-centered" style="margin-top: 4%">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Sign up</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                    <hr class="has-background-grey-lighter">
                    <div class="is-size-5 has-text-grey-light">Already have an account?</div>
                    <a href="{% url 'users:sign_in' %}" class="button is-ghost">
                        Move to login page
                    </a>
                </form>a
            </div>
        </div>
    </div>
{% endblock %}