config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'config'), namespace='shop')),
    path('users/', include(('users.urls', 'config'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('products/', views.products_list, name='products'),
    path('cart/', views.cart, name='cart'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_item/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('orders/', views.orders, name='orders')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password')
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    price = models.IntegerField()
    description = models.TextField()
    is_new = models.BooleanField(default=False)
    is_discounted = models.BooleanField(default=False)
    category = models.ForeignKey('shop.Category', default=None, on_delete=models.CASCADE)
    brand = models.ForeignKey('shop.Brand', default=None, on_delete=models.CASCADE)
    thumb = models.ImageField(default='default.jpg')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'shop_products'


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_categories'


class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_brands'


class Slide(models.Model):
    image = models.ImageField(default='slide.jpg')


class CartItem(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    def total_price(self):
        return self.product.price * self.quantity


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    phone = models.IntegerField()
    total_price = models.IntegerField()

    def __str__(self):
        return f"Order #{self.pk}"


class OrderProduct(models.Model):
    order = models.ForeignKey('shop.Order', on_delete=models.CASCADE, related_name='order_products')
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE)
    amount = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return f"{self.product} x{self.amount} - {self.order.customer.username}"


RATE_CHOICES = [
    (1, 'Trash'),
    (2, 'Bad'),
    (3, 'Ok'),
    (4, 'Good'),
    (5, 'Perfect'),
]


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(blank=True)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)

shop/forms.py
from django import forms
from .bulma_mixin import BulmaMixin
from .models import Order
from .models import Review, RATE_CHOICES


class OrderForm(BulmaMixin, forms.Form):
    address = forms.CharField(label='Write your address')
    phone = forms.CharField(label='Write your phone')

    class Meta:
        model = Order
        fields = ('address', 'phone')


class RateForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}),
                           label='Write review text'
                           )
    rate = forms.ChoiceField(choices=RATE_CHOICES,
                             required=True,
                             label='Rate product from 1 to 5'
                             )

    class Meta:
        model = Review
        fields = ('text', 'rate')

shop/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from shop import forms
from shop.forms import RateForm, OrderForm
from shop.models import Product, Slide, CartItem, Order, OrderProduct, Review


@login_required(login_url='/users/sign_in')
def products_list(request):
    products = Product.objects.all()
    slides = Slide.objects.all()
    category = request.GET.get('category')
    brand = request.GET.get('brand')
    search = request.GET.get('search')
    product_id = request.GET.get('product')
    if product_id:
        product = get_object_or_404(Product, pk=product_id)
        cart_item = CartItem.objects.filter(product=product, customer=request.user)
        if not cart_item:
            CartItem.objects.create(customer=request.user, product=product, quantity=1)
            return redirect('shop:products')
        for item in cart_item:
            item.quantity += 1
            item.save()
    products = products.filter(category=category) if category else products
    products = products.filter(brand=brand) if brand else products
    products = products.filter(Q(title__icontains=search) |
                               Q(description__icontains=search)) if search else products
    return render(request, 'products.html', {
        'products': products,
        'slides': slides
    })


def cart(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    total_price = sum([item.total_price() for item in cart_items])
    total_quantity = sum([item.quantity for item in cart_items])
    return render(request, 'cart.html', {
        'cart_items': cart_items,
        'total_price': total_price,
        'total_quantity': total_quantity,
    })


def delete_cart_item(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk).delete()
    return redirect('shop:cart')


def edit_cart_item(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk)
    action = request.GET.get('action')

    if action == 'take' and cart_item.quantity > 0:
        if cart_item.quantity == 1:
            cart_item.delete()
            return redirect('shop:cart')
        cart_item.quantity -= 1
        cart_item.save()
        return redirect('shop:cart')
    cart_item.quantity += 1
    cart_item.save()
    return redirect('shop:cart')


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    reviews = Review.objects.filter(product=product)
    form = RateForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.product = product
        instance.save()
        return redirect('shop:product_detail', pk=product.pk)
    return render(request, 'product_detail.html', {
        'product': product,
        'reviews': reviews,
        'form': form
    })


def create_order(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    total_price = sum([item.total_price() for item in cart_items])
    total_quantity = sum([item.quantity for item in cart_items])

    form = OrderForm(request.POST)

    if not cart_items:
        return render(request, 'error.html')

    if request.method == 'POST' and form.is_valid():
        order = Order.objects.create(
            customer=request.user,
            address=request.POST.get('address'),
            phone=request.POST.get('phone'),
            total_price=total_price
        )
        for cart_item in cart_items:
            OrderProduct.objects.create(
                order=order,
                product=cart_item.product,
                amount=cart_item.quantity,
                total=cart_item.total_price()
            )
        cart_items.delete()
        return redirect('shop:cart')

    return render(request, 'order_creation_page.html', {
        'cart_items': cart_items,
        'total_price': total_price,
        'total_quantity': total_quantity,
        'form': form
    })

def orders(request):
    orders_list = Order.objects.filter(customer=request.user)
    return render(request, 'orders.html', {
        'orders': orders_list
    })

shop/templates/base.html
{% load static %}
{% load brand %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <script type="module"
            src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>
<section class="hero">
    <div class="hero-head">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url "shop:products" %}">
                    <img src="{% static 'uploads/Monday(1).svg' %}" width="112" height="28">
                </a>
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                   data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            {% if user.is_authenticated %}
                <div class="navbar-start">
                    {% brands %}
                </div>
                <div class="navbar-end">
                    <form action="{% url 'shop:products' %}" method="get">
                        <div class="field has-addons mt-4 mr-2">
                            <div class="control">
                                <input class="input" type="search" placeholder="Find a product" name="search">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit">
                                    Search
                                </button>
                            </div>
                        </div>
                    </form>

                    <a class="navbar-item order" href="{% url 'shop:orders' %}">
                        <button class="button is-dark">
                            Orders
                        </button>
                    </a>

                    <a class="navbar-item order" href="{% url 'shop:cart' %}">
                        <button class="button is-success">
                            <ion-icon name="cart-outline" class="mr-2"></ion-icon>
                            Cart
                        </button>
                    </a>

                    <span class="navbar-item">
                       <div class="dropdown is-hoverable">
                           <div class="dropdown-trigger">
                               <button class="button is-warning" aria-haspopup="true" aria-controls="dropdown-menu">
                                   Welcome <span class="has-text-weight-bold mx-1">{{ user }}</span>
                               </button>
                           </div>
                           <div class="dropdown-menu" id="dropdown-menu" role="menu">
                               <div class="dropdown-content">
                                   <a href="{% url 'users:edit_profile' %}" class="dropdown-item">
                                       Edit profile
                                   </a>
                                   <a href="{% url 'users:reset_password' %}" class="dropdown-item">
                                       Reset password
                                   </a>
                                   <hr class="dropdown-divider">
                                   <a href="{% url 'users:sign_out' %}" class="dropdown-item">
                                       Sign out
                                   </a>
                               </div>
                           </div>
                       </div>
                    </span>


                </div>
            {% endif %}
        </nav>
    </div>
    <div class="hero-body">
        {% block auth %}
        {% endblock %}

        {% block slider %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
<script>
    bulmaCarousel.attach('#carousel-demo', {
        slidesToScroll: 1,
        slidesToShow: 1,
        infinite: true,
    });
</script>

</body>
</html>

shop/templates/brands.html
{% for brand in brands %}
    <a href="{% url 'shop:products' %}?brand={{ brand.pk }}" class="navbar-item">
        {{ brand }}
    </a>
{% endfor %}

shop/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="card mb-4 p-4 has-text-weight-bold is-size-4">
        <a class="button has-text-left is-danger" href="{% url 'shop:products' %}">Back to main page</a>
        {% if cart_items %}
            <a class="button has-text-right is-info" href="{% url 'shop:create_order' %}">Checkout</a>
        {% endif %}
        <hr>
        <div class="columns has-text-centered">
            <div class="column">
                <div class="content">Items: {{ total_quantity }}</div>
            </div>
            <div class="column">
                <div class="content">Total: {{ total_price }} sum</div>
            </div>
        </div>
    </div>
    <div class="card p-5">
        <div class="content">
            {% if cart_items %}
                {a class="button has-text-right is-info" href="{% url 'shop:create_order' %}">Checkout</a>

                <table class="table has-text-centered">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td>
                                <img src="{{ item.product.thumb.url }}" alt="" width="100" height="100">
                            </td>
                            <td>{{ item }}</td>
                            <td>{{ item.product.price }} sum</td>
                            <td>
                                <div class="quantity ml-3">
                                    <a href="{% url 'shop:edit_cart_item' item.id %}?action=add">
                                        <h1 class="title has-text-success">+</h1>
                                    </a>
                                    {{ item.quantity }}
                                    <a href="{% url 'shop:edit_cart_item' item.id %}?action=take">
                                        <h1 class="title has-text-danger">-</h1>
                                    </a>
                                </div>
                            </td>
                            <td>{{ item.total_price }} sum</td>
                            <td>
                                <a href="{% url 'shop:delete_cart_item' item.pk %}"
                                   style="font-size: 20px; color: black">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="title is-2 has-text-grey-light has-text-centered">Nothing added</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

shop/templates/categories.html
<aside class="menu has-background-info-light p-4" style="min-height: 100%; border-radius: 10px">
    <p class="menu-label is-size-3">
        Categories
    </p>
    <ul class="menu-list">
        {% for category in categories %}
            <li>
                <a href="{% url 'shop:products' %}?category={{ category.pk }}" class="dropdown-item is-size-5">
                    {{ category }}
                </a>
            </li>
        {% endfor %}
    </ul>
</aside>

shop/templates/error.html
{% extends 'base.html' %}

{% block content %}
    <div class="has-text-centered">
        <div class="columns is-centered" style="margin-top: 100px">
            <div class="column is-5">
                <div class="box">
                    <p class="title is-3">You did not add anything to cart</p>
                    <a href="{% url 'shop:cart' %}" class="button is-success is-fullwidth">Back to cart</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/file_input.html
<div class="file">
    <label class="file-label">
        <input type="{{ widget.type }}" class="file-input" name="{{ widget.name }}"
                {% if widget.value != None %}
               value="{{ widget.value|stringformat:'s' }}"
                {% endif %}
                {% include "django/forms/widgets/attrs.html" %}>
        <span class="file-cta">
               <ion-icon name="cloud-upload-outline" class="mr-2"></ion-icon>
               <span class="file-label">
                   Choose a file…
               </span>
           </span>
    </label>
</div>

shop/templates/order_creation_page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="box">
                    <form method="post" action="{% url 'shop:create_order' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="title">
                            Shipping Information:
                        </div>
                        {% for field in form %}
                            <div class="field">
                                <label for="{{ field.id_for_label }}" class="label"></label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="button is-fullwidth is-success">Submit</button>
                    </form>
                </div>
            </div>
            <div class="column is-6">
                <div class="box">
                    <a class="button is-danger" href="{% url 'shop:cart' %}">Back to cart</a
                    <hr>
                    <div class="title">Order Summary</div>
                    <table class="table is-fullwidth">
                        <thead>
                        <tr class="has-text-weight-bold">
                            <td></td>
                            <td>Product</td>
                            <td>Price</td>
                            <td>Quantity</td>
                            <td>Total</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in cart_items %}
                            <tr>
                                <td>
                                    <img src="{{ item.product.thumb.url }}" alt="" width="50" height="50">
                                </td>
                                <td>{{ item }}</td>
                                <td>{{ item.product.price }} sum</td>
                                <td>x {{ item.quantity }}</td>
                                <td>{{ item.total_price }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="title is-size-4">Total: {{ total_price }} sum </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="card p-5">
            <div class="content">
                {% if orders %}
                    <div class="title has-text-centered">My recent orders</div>
                    <table class="table has-text-centered">
                        <thead>
                        <tr>
                            <th>Order number</th>
                            <th>Products</th>
                            <th>Total</th>
                            <th>Status</th>
                            <th>Payed</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order }}</td>
                                <td>
                                    {% for order_product in order.order_products.all %}
                                        <a href="{% url 'shop:product_detail' order_product.product.pk %}">
                                            {{ order_product }}
                                        </a>,
                                    {% endfor %}
                                </td>
                                <td>{{ order.total_price }} sum</td>
                                <td>In consideration</td>
                                <td>Not paid</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="title has-text-centered">Nothing ordered yet</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="section product-detail">
        <div class="columns is-flex is-align-items-center">
            <div class="column">
                <div class="box">
                    <figure class="image product-detail-image">
                        <img src="{{ product.thumb.url }}" alt="Placeholder image">
                    </figure>
                </div>
            </div>
            <div class="column">
                <div class="content">
                    <p class="title is-size-2">
                        {{ product.title }}
                        {% if product.is_new %}
                            <span class="tag is-danger">New!</span>
                        {% endif %}
                        {% if product.is_discounted %}
                            <span class="tag is-primary">Discount!</span>
                        {% endif %}
                    </p>
                    <p class="title is-size-3 has-text-info">{{ product.price }} sum</p>
                    <p class="title is-size-5 has-text-grey-light">0 отзывов</p>
                    <p class="title">Brand: {{ product.brand }}</p>
                    <p class="title has-text-grey-light is-size-4">Наличие: Есть в наличии</p>
                    <p class="title is-size-4">
                        Поделится:
                        <span class="is-size-4 mx-3">
                           <a href="#">
                               <ion-icon name="logo-whatsapp" class="order"></ion-icon>
                           </a>
                           <a href="#">
                               <ion-icon name="logo-youtube" class="order"></ion-icon>
                           </a>
                           <a href="#">
                               <ion-icon name="logo-facebook" class="order"></ion-icon>
                           </a>
                       </span>
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name == 'rate' %}
                                <div class="select is-fullwidth mb-4">
                                    <label for="{{ field.id_for_label }}"
                                           class="label is-size-4">{{ field.label }}</label>
                                    {{ field }}
                                </div>
                            {% else %}
                                <div class="field">
                                    <label for="{{ field.id_for_label }}" class="label is-size-4">
                                        {{ field.label }}
                                    </label>
                                    {{ field }}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div class="mt-6">
                            <button class='button is-success' type="submit">Submit</button>
                            <a class='button is-danger' href="{% url 'shop:product_detail' product.pk %}">Back to main
                                page</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <hr>
        <div class="section">
            {% if reviews %}
                <div class="title is-size-3 has-text-centered">Reviews of other clients</div>
                <div class="columns is is-multiline is-centered mt-6">
                    {% for review in reviews %}
                        <div class="column is-4">
                            <div class="card">
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-left">
                                            <figure class="image is-48x48">
                                                <img src="https://www.winhelponline.com/blog/wp-content/uploads/2017/12/user.png"
                                                     alt="Placeholder image" class="is-rounded">
                                            </figure>
                                        </div>
                                        <div class="media-content">
                                            <p class="title is-size-4">{{ review.user.first_name }}</p>
                                            <p class="subtitle">@{{ review.user }}</p>
                                        </div>
                                    </div>
                                    <div class="content">
                                        <div>
                                            {{ review.rate }}/5
                                            <ion-icon name="star-outline"></ion-icon>
                                            <span class="mx-2 has-text-grey-light">{{ review.date }}</span>
                                        </div>
                                    </div>
                                    <div class="subtitle has-text-grey">
                                        {{ review.text }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="title is-size-3 has-text-centered">No reviews yet. Be first to leave one</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

shop/templates/products.html
{% extends 'base.html' %}
{% load category %}

{% block slider %}
    <div class="container-slide mb-6">
        <div id="carousel-demo" class="carousel">
            {% for slide in slides %}
                <div class="item-1">
                    <img class="slider-img" src="{{ slide.image.url }}" alt="">
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="columns mt-2">
        <div class="column is-one-fifth">
            {% categories %}
        </div>
        <div class="column">
            <div class="columns is-multiline is-centered">
                {% for product in products %}
                    <div class="column is-4">
                        <a href="{% url 'shop:product_detail' product.pk %}">
                            <div class="card product-card" style="min-height: 520px">
                                <div class="card-image">
                                    <figure class="image">
                                        <img src="{{ product.thumb.url }}" alt="Placeholder image"
                                             style="min-height: 340px">
                                    </figure>
                                    <div class="has-text-right m-3">
                                        {% if product.is_new %}
                                            <span class="tag is-danger">New!</span>
                                        {% endif %}
                                        {% if product.is_discounted %}
                                            <span class="tag is-primary">Discount!</span>
                                        {% endif %}
                                    </div>

                                </div>
                                <div class="card-content">
                                    <div class="media">
                                        <br>
                                        <div class="media-content">
                                            <p class="title is-4">{{ product }}</p>
                                        </div>
                                    </div>
                                    <div class="content has-text-weight-bold">
                                        <div class="columns">
                                            <div class="column">
                                                {{ product.price }} sum
                                            </div>
                                            <div class="column has-text-right">
                                                <a href="{% url 'shop:products' %}?product={{ product.id }}">
                                                    <ion-icon name="cart-outline" class="order"></ion-icon>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}